name: Tests
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.3.12", "3.4.10", "4.0.6", "head"]
        rails: ["7.2", "8.0", "8.1"]
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Ruby environment
        uses: ./.github/actions/setup-ruby
        with:
          ruby_version: ${{ matrix.ruby }}

      - name: Run tests
        shell: sh
        run: bundle exec rspec spec
